name: Check mathpix CRAN status

on:
  schedule:
    # Runs daily at 5:00 PM UTC
    - cron: '0 17 * * *'  
  # allows for manually running of the check
  workflow_dispatch:

jobs:
  check_cran_status:
    runs-on: ubuntu-latest

    steps:
      - name: Get CRAN checks
        uses: flrsh-dev/cran-checks/check-pkg@main
        with:
          pkg: mathpix
